name: Medusa B2B Deploy

on:
  push:
    branches:
      - main # Убедитесь, что это имя вашей основной ветки (например, master)

jobs:
  deploy:
    runs-on: ubuntu-latest # Вы можете использовать self-hosted runner, если нужно

    steps:
      - name: Checkout code
        # Выгружает код из вашего репозитория
        uses: actions/checkout@v4

      # Пропускаем шаги сборки (например, yarn install, build) на CI runner,
      # поскольку они будут выполнены вручную на сервере в первый раз.

      - name: Copy project files to server
        # Используем action для копирования файлов по SCP
        uses: appleboy/scp-action@v0.1.4 # Проверьте наличие более новой версии, если хотите
        with:
          host: ${{ secrets.SSH_HOST }} # IP-адрес сервера из секретов GitHub
          username: ${{ secrets.SSH_USER }} # Имя пользователя SSH из секретов GitHub
          key: ${{ secrets.SERVER_SSH_KEY }} # Приватный SSH-ключ из секретов GitHub
          port: ${{ secrets.SSH_PORT }} # Порт SSH из секретов GitHub (опционально, по умолчанию 22)
          source: "./" # Копируем все файлы и папки из корня репозитория
          target: "/home/admin2/medusa-b2b" # Целевая директория на сервере
          # Опционально: исключите определенные директории/файлы при копировании
          # exclude: ".git,.github,node_modules,dist"

      - name: Restart Medusa service via PM2
        # Используем action для выполнения команды по SSH
        uses: appleboy/ssh-action@v1.0.0 # Проверьте наличие более новой версии, если хотите
        with:
          host: ${{ secrets.SSH_HOST }} # IP-адрес сервера из секретов GitHub
          username: ${{ secrets.SSH_USER }} # Имя пользователя SSH из секретов GitHub
          key: ${{ secrets.SERVER_SSH_KEY }} # Приватный SSH-ключ из секретов GitHub
          port: ${{ secrets.SSH_PORT }} # Порт SSH из секретов GitHub (опционально, по умолчанию 22)
          script: |
            # Переходим в директорию проекта на сервере
            cd /home/admin2/medusa-b2b

            # --- ВАЖНО ---
            # Этот рабочий процесс ПРЕДПОЛАГАЕТ, что вы ВРУЧНУЮ выполнили ПЕРВОНАЧАЛЬНУЮ настройку
            # (yarn install, настройка БД, создание пользователя, запуск через PM2)
            # ПОСЛЕ САМОГО ПЕРВОГО успешного копирования файлов этим рабочим процессом.

            # Для последующих запусков эта команда перезапускает процесс PM2.
            # Замените 'medusa-b2b' на фактическое имя вашего процесса PM2.
            # Если PM2 не запущен или имя процесса неверно, эта команда может завершиться с ошибкой.
            echo "Попытка перезапустить процесс PM2 'medusa-b2b'..."
            pm2 restart medusa-b2b || echo "Не удалось перезапустить процесс PM2 'medusa-b2b'. Возможно, он не запущен или имя неверно. Проверьте вручную на сервере."
